const crypto = require("node:crypto");
const { streetAddressKey } = require("./calendar-sync");

const AIRTABLE_API_URL = "https://api.airtable.com/v0";

function clean(value) {
  return value === undefined || value === null ? "" : String(value).trim();
}

function constantTimeEqual(left, right) {
  const a = Buffer.from(clean(left));
  const b = Buffer.from(clean(right));
  return a.length > 0 && a.length === b.length && crypto.timingSafeEqual(a, b);
}

function bearerToken(headers = {}) {
  const authorization = clean(headers.authorization || headers.Authorization);
  const match = authorization.match(/^Bearer\s+(.+)$/i);
  return match ? clean(match[1]) : clean(headers["x-render-intake-token"] || headers["X-Render-Intake-Token"]);
}

function intakeAuthorized(headers = {}, expectedToken = process.env.RENDER_INTAKE_TOKEN) {
  return Boolean(clean(expectedToken)) && constantTimeEqual(bearerToken(headers), expectedToken);
}

function validateIntakeEnvelope(body) {
  if (!body || typeof body !== "object" || Array.isArray(body)) {
    return { ok: false, error: "Request body must be an object" };
  }
  if (body.version !== 1) return { ok: false, error: "Unsupported intake payload version" };
  if (clean(body.source) !== "netlify-fpd-intake") return { ok: false, error: "Invalid intake source" };
  if (!body.fields || typeof body.fields !== "object" || Array.isArray(body.fields)) {
    return { ok: false, error: "A normalized fields object is required" };
  }
  if (!clean(body.fields["Property Address"])) return { ok: false, error: "Property address is required" };
  const idempotencyKey = clean(body.idempotencyKey);
  if (idempotencyKey && !/^[A-Za-z0-9._:-]{1,160}$/.test(idempotencyKey)) {
    return { ok: false, error: "Invalid idempotency key" };
  }
  return { ok: true, idempotencyKey };
}

function airtableSettings(env = process.env) {
  return {
    token: clean(env.AIRTABLE_TOKEN),
    baseId: clean(env.AIRTABLE_BASE_ID),
    table: clean(env.AIRTABLE_JOBS_TABLE_ID || env.AIRTABLE_JOBS_TABLE) || "Jobs"
  };
}

function unknownFieldName(errorBody) {
  const message = errorBody && errorBody.error && errorBody.error.message;
  const match = String(message || "").match(/Unknown field name: "([^"]+)"/);
  return match ? match[1] : "";
}

async function airtableFetch(url, { token, method = "GET", body } = {}) {
  const response = await fetch(url, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/json",
      ...(body ? { "Content-Type": "application/json" } : {})
    },
    ...(body ? { body: JSON.stringify(body) } : {})
  });
  const result = await response.json().catch(() => ({}));
  return { response, result };
}

async function findExistingByJobId({ settings, jobId }) {
  if (!clean(jobId)) return null;
  const url = new URL(`${AIRTABLE_API_URL}/${encodeURIComponent(settings.baseId)}/${encodeURIComponent(settings.table)}`);
  // Job IDs are generated by the intake function and restricted to a safe charset.
  url.searchParams.set("filterByFormula", `{Job ID}='${clean(jobId).replaceAll("'", "\\'")}'`);
  url.searchParams.set("maxRecords", "1");
  const { response, result } = await airtableFetch(url.href, { token: settings.token });
  if (!response.ok) throw new Error(`Airtable lookup failed with status ${response.status}`);
  return Array.isArray(result.records) && result.records.length ? result.records[0] : null;
}

async function findExistingByAddressAndEmail({ settings, propertyAddress, clientEmail, now = Date.now(), lookbackDays = 120 }) {
  const addressKey = streetAddressKey(propertyAddress);
  const email = clean(clientEmail).toLowerCase();
  if (!addressKey || !email) return null;
  const url = new URL(`${AIRTABLE_API_URL}/${encodeURIComponent(settings.baseId)}/${encodeURIComponent(settings.table)}`);
  url.searchParams.set("maxRecords", "500");
  const { response, result } = await airtableFetch(url.href, { token: settings.token });
  if (!response.ok) throw new Error(`Airtable address lookup failed with status ${response.status}`);
  const cutoff = now - Math.max(1, Number(lookbackDays) || 120) * 24 * 60 * 60 * 1000;
  const matches = (Array.isArray(result.records) ? result.records : []).filter((record) => {
    const fields = record && record.fields || {};
    const created = Date.parse(record && record.createdTime);
    return streetAddressKey(fields["Property Address"] || fields.Address) === addressKey
      && clean(fields["Client Email"] || fields.Email).toLowerCase() === email
      && (!Number.isFinite(created) || created >= cutoff);
  });
  return matches.sort((left, right) => Date.parse(right.createdTime || 0) - Date.parse(left.createdTime || 0))[0] || null;
}

async function createAirtableIntakeRecord({ fields, env = process.env }) {
  const settings = airtableSettings(env);
  if (!settings.token || !settings.baseId) throw new Error("Airtable is not configured for Render intake");

  const existing = await findExistingByJobId({ settings, jobId: fields["Job ID"] });
  if (existing) return { record: existing, duplicate: true, omittedFields: [] };

  // Website retries often generate a fresh Job ID even though the same client
  // just submitted the same property. Match the stable street + client email
  // signature within a short operational window before creating a new row.
  const contactMatch = await findExistingByAddressAndEmail({
    settings,
    propertyAddress: fields["Property Address"],
    clientEmail: fields["Client Email"],
    lookbackDays: env.DUPLICATE_LOOKBACK_DAYS || 120
  });
  if (contactMatch) return { record: contactMatch, duplicate: true, omittedFields: [] };

  const url = `${AIRTABLE_API_URL}/${encodeURIComponent(settings.baseId)}/${encodeURIComponent(settings.table)}`;
  const remainingFields = { ...fields };
  const omittedFields = [];
  for (let attempt = 0; attempt < 24; attempt += 1) {
    const { response, result } = await airtableFetch(url, {
      token: settings.token,
      method: "POST",
      body: { fields: remainingFields, typecast: true }
    });
    if (response.ok) return { record: result, duplicate: false, omittedFields };
    const fieldName = unknownFieldName(result);
    if (!fieldName || !(fieldName in remainingFields)) {
      const error = new Error((result.error && result.error.message) || `Airtable create failed with status ${response.status}`);
      error.status = response.status;
      error.body = result;
      throw error;
    }
    omittedFields.push(fieldName);
    delete remainingFields[fieldName];
  }
  throw new Error("Too many Airtable fields were missing from the target table");
}

module.exports = {
  airtableSettings,
  bearerToken,
  constantTimeEqual,
  createAirtableIntakeRecord,
  findExistingByAddressAndEmail,
  findExistingByJobId,
  intakeAuthorized,
  validateIntakeEnvelope
};
