function portalPage() {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="noindex,nofollow">
  <title>FloorPlanDrawings · Master</title>
  <style>
    :root{--ink:#25332f;--muted:#718078;--paper:#fbfaf6;--card:#fff;--line:#e4e8e0;--sage:#dce8dc;--sage-strong:#a8c5ae;--forest:#194b3e;--gold:#e0b75c;--danger:#a94444;--shadow:0 18px 48px rgba(38,61,54,.09)}
    *{box-sizing:border-box} body{margin:0;background:linear-gradient(145deg,#f5f6f0 0%,var(--paper) 46%,#eef4ee 100%);color:var(--ink);font:16px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
    button,input,select,textarea{font:inherit} button{cursor:pointer}
    .shell{max-width:1440px;margin:0 auto;padding:28px clamp(18px,4vw,54px) 72px}.topbar{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:28px}.brand{display:flex;align-items:center;gap:14px}.mark{width:42px;height:42px;border-radius:14px;background:var(--forest);display:grid;place-items:center;color:#fff;font-weight:800;letter-spacing:.08em}.eyebrow{font-size:12px;letter-spacing:.18em;text-transform:uppercase;color:var(--muted);font-weight:750}.brand h1{font-size:24px;line-height:1.1;margin:3px 0 0;letter-spacing:-.03em}.pill{display:inline-flex;align-items:center;border:1px solid var(--line);background:rgba(255,255,255,.8);border-radius:999px;padding:7px 12px;font-size:13px;color:var(--muted)}
    .hero{display:flex;justify-content:space-between;align-items:end;gap:24px;margin:8px 0 22px}.hero h2{font-size:clamp(30px,4vw,48px);line-height:1.02;letter-spacing:-.055em;margin:8px 0 10px}.hero p{margin:0;color:var(--muted);max-width:610px}.hero-actions{display:flex;gap:10px;flex-wrap:wrap}.button{border:0;border-radius:12px;padding:11px 16px;font-weight:700;background:var(--forest);color:#fff;box-shadow:0 8px 18px rgba(25,75,62,.16)}.button.secondary{background:#fff;color:var(--forest);border:1px solid var(--line);box-shadow:none}.button:disabled{opacity:.55;cursor:not-allowed}
    .toolbar{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap;margin:26px 0 18px}.chips{display:flex;gap:8px;flex-wrap:wrap}.chip{border:1px solid var(--line);background:rgba(255,255,255,.72);color:var(--muted);border-radius:999px;padding:8px 13px;font-size:14px}.chip.active{background:var(--forest);border-color:var(--forest);color:#fff}.search{min-width:min(360px,100%);border:1px solid var(--line);background:#fff;border-radius:12px;padding:11px 14px;outline:none}.search:focus{border-color:var(--sage-strong);box-shadow:0 0 0 3px rgba(168,197,174,.25)}
    .summary{display:flex;gap:10px;align-items:center;color:var(--muted);font-size:14px}.summary strong{color:var(--ink)}.jobs{display:grid;grid-template-columns:repeat(auto-fill,minmax(min(100%,370px),1fr));gap:16px}.job{background:rgba(255,255,255,.9);border:1px solid var(--line);border-radius:20px;padding:20px;box-shadow:var(--shadow);display:flex;flex-direction:column;gap:15px;min-height:275px}.job-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.job h3{font-size:21px;line-height:1.16;margin:5px 0 0;letter-spacing:-.03em}.job .address{color:var(--muted);font-size:14px;margin-top:6px}.status{display:inline-flex;align-items:center;white-space:nowrap;border-radius:999px;padding:6px 10px;background:var(--sage);color:var(--forest);font-size:12px;font-weight:800;letter-spacing:.04em;text-transform:uppercase}.status.warning{background:#fff1d1;color:#8a641b}.status.muted{background:#eef0ed;color:#69756e}.meta{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.meta-item{border:1px solid var(--line);border-radius:12px;padding:10px 11px;background:#fcfdfb}.meta-item span{display:block;color:var(--muted);font-size:11px;letter-spacing:.08em;text-transform:uppercase;font-weight:750}.meta-item strong{display:block;margin-top:3px;font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.links{display:flex;gap:8px;flex-wrap:wrap;margin-top:auto}.link{border:1px solid var(--line);border-radius:10px;background:#fff;color:#1762c4;text-decoration:none;padding:7px 10px;font-size:13px;font-weight:700}.card-actions{display:flex;justify-content:space-between;align-items:center;gap:10px}.edit{border:0;background:transparent;color:var(--forest);font-weight:800;padding:6px 0}.empty{grid-column:1/-1;background:rgba(255,255,255,.75);border:1px dashed #cdd8cf;border-radius:18px;padding:38px;text-align:center;color:var(--muted)}
    .backdrop{position:fixed;inset:0;background:rgba(24,39,34,.34);display:none;align-items:center;justify-content:center;padding:18px;z-index:5}.backdrop.open{display:flex}.panel{width:min(680px,100%);max-height:calc(100vh - 36px);overflow:auto;background:var(--paper);border-radius:22px;padding:24px;box-shadow:0 28px 80px rgba(13,34,28,.24)}.panel-head{display:flex;justify-content:space-between;gap:15px;align-items:flex-start}.panel h2{font-size:28px;line-height:1.1;margin:7px 0}.close{border:0;background:transparent;color:var(--muted);font-size:24px}.form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:22px}.field{display:flex;flex-direction:column;gap:6px}.field.full{grid-column:1/-1}.field label{font-size:12px;letter-spacing:.1em;text-transform:uppercase;color:var(--muted);font-weight:800}.field input,.field select,.field textarea{border:1px solid var(--line);border-radius:11px;background:#fff;padding:11px 12px;color:var(--ink);outline:none}.field textarea{min-height:84px;resize:vertical}.panel-foot{display:flex;justify-content:flex-end;gap:10px;margin-top:20px}.notice{margin-top:14px;padding:11px 13px;border-radius:11px;background:#fff1d1;color:#76561a;font-size:13px}.login{position:fixed;inset:0;background:linear-gradient(145deg,#edf4ee,#fbfaf6);display:flex;align-items:center;justify-content:center;padding:20px;z-index:10}.login.hidden{display:none}.login-card{width:min(430px,100%);background:#fff;border:1px solid var(--line);border-radius:22px;padding:28px;box-shadow:var(--shadow)}.login-card h2{margin:8px 0;font-size:30px;letter-spacing:-.05em}.login-card p{color:var(--muted);margin:0 0 20px}.login-card input{width:100%;border:1px solid var(--line);border-radius:11px;padding:12px}.login-card .button{width:100%;margin-top:12px}.error{color:var(--danger);font-size:13px;margin-top:10px;min-height:20px}.toast{position:fixed;right:18px;bottom:18px;background:var(--forest);color:#fff;padding:12px 15px;border-radius:12px;box-shadow:var(--shadow);display:none;z-index:20}.toast.show{display:block}
    @media(max-width:700px){.shell{padding-top:18px}.topbar,.hero{align-items:flex-start;flex-direction:column}.hero-actions{width:100%}.hero-actions .button{flex:1}.toolbar{align-items:stretch}.search{width:100%;min-width:0}.meta{grid-template-columns:1fr 1fr}.form{grid-template-columns:1fr}.field.full{grid-column:auto}.job{border-radius:16px;padding:17px}}
  </style>
</head>
<body>
  <div id="login" class="login">
    <div class="login-card">
      <div class="eyebrow">FloorPlanDrawings · internal</div>
      <h2>Master workspace</h2>
      <p>Enter Anna’s internal admin token to load the operational dashboard. It stays in this browser tab and is never saved.</p>
      <input id="token" type="password" autocomplete="off" placeholder="Internal admin token">
      <button id="loginButton" class="button">Open workspace</button>
      <div id="loginError" class="error"></div>
    </div>
  </div>
  <main class="shell">
    <header class="topbar"><div class="brand"><div class="mark">FPD</div><div><div class="eyebrow">Operations</div><h1>FloorPlanDrawings</h1></div></div><span class="pill">Airtable-backed · internal</span></header>
    <section class="hero"><div><div class="eyebrow">Master workspace</div><h2>See the work. Move it forward.</h2><p>A calmer front door to the Jobs table, with the links and decisions Anna uses most.</p></div><div class="hero-actions"><button id="refresh" class="button secondary">Refresh jobs</button><button id="logout" class="button secondary">Lock workspace</button></div></section>
    <div class="toolbar"><div id="chips" class="chips"></div><input id="search" class="search" type="search" placeholder="Search client or address"></div>
    <div class="summary"><strong id="count">0 jobs</strong><span>·</span><span id="lastUpdated">Not loaded</span></div>
    <section id="jobs" class="jobs" aria-live="polite"></section>
  </main>
  <div id="backdrop" class="backdrop"><section class="panel" role="dialog" aria-modal="true" aria-labelledby="editTitle"><div class="panel-head"><div><div class="eyebrow">Job editor</div><h2 id="editTitle">Edit job</h2><div id="editAddress" class="address"></div></div><button id="closePanel" class="close" aria-label="Close">×</button></div><form id="editForm" class="form"><div class="field"><label for="clientName">Client</label><input id="clientName" name="clientName"></div><div class="field"><label for="status">Status</label><select id="status" name="status"><option>New Request</option><option>Needs Quote</option><option>Quote Sent</option><option>Waiting On Client</option><option>Accepted</option><option>Needs Scheduling</option><option>Scheduled</option><option>Measured</option><option>Drawing In Progress</option><option>Ready For Review</option><option>Delivered</option><option>Invoiced</option><option>Paid</option><option>Lost / Canceled</option><option>In Progress</option><option>Completed</option><option>Calendar Imported</option></select></div><div class="field"><label for="assignedMeasurer">Employee assigned</label><input id="assignedMeasurer" name="assignedMeasurer" placeholder="Ricky, Corrie, Sarah"></div><div class="field"><label for="approxSqFt">Estimated sq ft</label><input id="approxSqFt" name="approxSqFt" inputmode="numeric"></div><div class="field"><label for="verifiedSqFt">Verified sq ft</label><input id="verifiedSqFt" name="verifiedSqFt" inputmode="numeric"></div><div class="field"><label for="appointment">Scheduled visit</label><input id="appointment" name="appointment" type="datetime-local"></div><div class="field"><label for="delivery">Promised delivery</label><input id="delivery" name="delivery" type="date"></div><div class="field full"><label for="accessInfo">Access info</label><textarea id="accessInfo" name="accessInfo"></textarea></div></form><div id="editNotice" class="notice" style="display:none"></div><div class="panel-foot"><button id="cancelEdit" type="button" class="button secondary">Cancel</button><button id="saveEdit" type="submit" form="editForm" class="button">Save changes</button></div></section></div>
  <div id="toast" class="toast" role="status"></div>
  <script>
    (() => {
      let adminToken = ""; let jobs = []; let employee = "all"; let editing = null;
      const $ = (id) => document.getElementById(id);
      const esc = (value) => String(value ?? "").replace(/[&<>\"]/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[char]));
      const fmtDate = (value) => { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleString([], {month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}); };
      const dateInput = (value) => { if (!value) return ""; const date = new Date(value); if (Number.isNaN(date.getTime())) return ""; const p = (n) => String(n).padStart(2,"0"); return date.getFullYear()+"-"+p(date.getMonth()+1)+"-"+p(date.getDate())+"T"+p(date.getHours())+":"+p(date.getMinutes()); };
      const showToast = (message) => { $("toast").textContent = message; $("toast").classList.add("show"); setTimeout(() => $("toast").classList.remove("show"), 2600); };
      const request = async (path, options = {}) => { const response = await fetch(path, { ...options, headers: { "Content-Type":"application/json", "X-Admin-Token":adminToken, ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "Request failed"); return body; };
      const statusClass = (status) => /need|review|missing/i.test(status || "") ? "warning" : !status ? "muted" : "";
      const sqFtLabel = (job) => job.verifiedSqFt ? "Confirmed" : job.approxSqFt ? "Estimate" : "Missing";
      const renderChips = () => { const names = ["all","ricky","corrie","sarah","unassigned"]; $("chips").innerHTML = names.map((name) => "<button class=\"chip " + (employee === name ? "active" : "") + "\" data-employee=\"" + name + "\">" + (name === "all" ? "All jobs" : name[0].toUpperCase()+name.slice(1)) + "</button>").join(""); document.querySelectorAll("[data-employee]").forEach((button) => button.addEventListener("click", () => { employee = button.dataset.employee; renderChips(); renderJobs(); })); };
      const filteredJobs = () => { const term = $("search").value.trim().toLowerCase(); return jobs.filter((job) => { const assigned = (job.assignedMeasurer || "").toLowerCase(); const employeeMatch = employee === "all" || (employee === "unassigned" ? !assigned : assigned.includes(employee)); const textMatch = !term || [job.clientName, job.propertyAddress, job.status, job.assignedMeasurer].some((value) => String(value || "").toLowerCase().includes(term)); return employeeMatch && textMatch; }); };
      const renderJobs = () => { const visible = filteredJobs(); $("count").textContent = visible.length + (visible.length === 1 ? " job" : " jobs"); if (!visible.length) { $("jobs").innerHTML = "<div class=\"empty\"><strong>No jobs match this view.</strong><br>Try another employee or search term.</div>"; return; } $("jobs").innerHTML = visible.map((job) => { const links = (job.googleMapsLink ? "<a class=\"link\" href=\"" + esc(job.googleMapsLink) + "\" target=\"_blank\" rel=\"noopener\">Maps</a>" : "") + (job.zimasLink ? "<a class=\"link\" href=\"" + esc(job.zimasLink) + "\" target=\"_blank\" rel=\"noopener\">ZIMAS</a>" : "") + ((job.satellitePhotoLink || job.mapUrl) ? "<a class=\"link\" href=\"" + esc(job.satellitePhotoLink || job.mapUrl) + "\" target=\"_blank\" rel=\"noopener\">Aerial</a>" : ""); return "<article class=\"job\"><div class=\"job-head\"><div><div class=\"eyebrow\">" + esc(job.service || job.workflow || "Floor plan request") + "</div><h3>" + esc(job.clientName || "Unassigned client") + "</h3><div class=\"address\">" + esc(job.propertyAddress || "Address pending") + "</div></div><span class=\"status " + statusClass(job.status) + "\">" + esc(job.status || "Open") + "</span></div><div class=\"meta\"><div class=\"meta-item\"><span>Employee</span><strong>" + esc(job.assignedMeasurer || "Unassigned") + "</strong></div><div class=\"meta-item\"><span>Square footage</span><strong>" + esc(job.verifiedSqFt || job.approxSqFt || "—") + " · " + sqFtLabel(job) + "</strong></div><div class=\"meta-item\"><span>Visit</span><strong>" + esc(fmtDate(job.appointmentDateTime || job.appointmentStart)) + "</strong></div><div class=\"meta-item\"><span>Delivery</span><strong>" + esc(fmtDate(job.deliveryDate)) + "</strong></div></div><div class=\"links\">" + links + "</div><div class=\"card-actions\"><span class=\"eyebrow\">" + esc(job.recordId || "") + "</span><button class=\"edit\" data-edit=\"" + esc(job.recordId) + "\">Edit job →</button></div></article>"; }).join(""); document.querySelectorAll("[data-edit]").forEach((button) => button.addEventListener("click", () => openEditor(jobs.find((job) => job.recordId === button.dataset.edit)))); };
      const loadJobs = async () => { try { const body = await request("/api/portal/jobs?limit=250"); jobs = body.jobs || []; $("lastUpdated").textContent = "Updated " + new Date().toLocaleTimeString([], {hour:"numeric",minute:"2-digit"}); renderChips(); renderJobs(); $("login").classList.add("hidden"); } catch (error) { $("loginError").textContent = error.message; $("login").classList.remove("hidden"); } };
      const openEditor = (job) => { if (!job) return; editing = job; $("editTitle").textContent = job.clientName || "Edit job"; $("editAddress").textContent = job.propertyAddress || "Address pending"; $("clientName").value = job.clientName || ""; $("status").value = job.status || "New Request"; $("assignedMeasurer").value = job.assignedMeasurer || ""; $("approxSqFt").value = job.approxSqFt || ""; $("verifiedSqFt").value = job.verifiedSqFt || ""; $("appointment").value = dateInput(job.appointmentDateTime || job.appointmentStart); $("delivery").value = job.deliveryDate ? String(job.deliveryDate).slice(0,10) : ""; $("accessInfo").value = job.accessInfo || ""; $("editNotice").style.display = "none"; $("backdrop").classList.add("open"); };
      const closeEditor = () => { editing = null; $("backdrop").classList.remove("open"); };
      $("loginButton").addEventListener("click", () => { adminToken = $("token").value.trim(); if (!adminToken) { $("loginError").textContent = "Enter the admin token to continue."; return; } loadJobs(); }); $("token").addEventListener("keydown", (event) => { if (event.key === "Enter") $("loginButton").click(); }); $("refresh").addEventListener("click", loadJobs); $("logout").addEventListener("click", () => { adminToken = ""; jobs = []; $("token").value = ""; $("loginError").textContent = ""; $("login").classList.remove("hidden"); }); $("search").addEventListener("input", renderJobs); $("closePanel").addEventListener("click", closeEditor); $("cancelEdit").addEventListener("click", closeEditor); $("backdrop").addEventListener("click", (event) => { if (event.target === $("backdrop")) closeEditor(); }); $("editForm").addEventListener("submit", async (event) => { event.preventDefault(); if (!editing) return; const button = $("saveEdit"); button.disabled = true; try { const fields = { "Client Name": $("clientName").value.trim(), Status: $("status").value, "Assigned Measurer": $("assignedMeasurer").value.trim(), "Approx Sq Ft": $("approxSqFt").value ? Number($("approxSqFt").value) : null, "Verified Sq Ft": $("verifiedSqFt").value ? Number($("verifiedSqFt").value) : null, "Appointment Date/Time": $("appointment").value ? new Date($("appointment").value).toISOString() : null, "Delivery Date": $("delivery").value || null, "Access Info": $("accessInfo").value.trim() }; await request("/api/portal/jobs/" + encodeURIComponent(editing.recordId), { method:"PATCH", body:JSON.stringify({ fields }) }); closeEditor(); await loadJobs(); showToast("Saved — Airtable is up to date."); } catch (error) { $("editNotice").textContent = error.message; $("editNotice").style.display = "block"; } finally { button.disabled = false; } });
    })();
  </script>
</body>
</html>`;
}

module.exports = { portalPage };
